hydra:
  run:
    # dynamic output directory according to running time and override name
    dir: hydraLog/${now:%Y-%m-%d-%H-%M-%S}-${mode}
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working direcotry unchaned
  sweep:
    # output directory for multirun
    dir: ${hydra.run.dir}
    subdir: ./

# model
model: "GNOFNOGNO_all"
radius_in: 0.035  # 0.045
radius_out: 0.035  # 0.045
embed_dim: 32  # 32
hidden_channels: [64, 64] # [64, 64]
in_channels: 2
out_channels: [1,3] # pressure + wss
fno_modes: [32, 32, 32] # [32, 32, 32]
fno_hidden_channels: 64 # 64
fno_out_channels: 64 # 64
weighted_kernel: false
max_in_points: 500000  # 500000
subsample_train: 8 # 1
subsample_eval: 1 # only set to 1 can get right Cd truth
out_keys: ["pressure","wallshearstress"]
sdf_spatial_resolution: [64, 64, 64] # or [64, 64, 64]

# data
data_module: SAE
n_train_num: 166 # 862
n_val_num: 1 #
n_test_num: 20 # 166
n_inference_num: 1
only_save_sdf: false  # generate sdf&closest_points or training
lazy_loading: true  # load all data into memory or not

# settings
enable_ddp: true
devices: [1, 2]  # python -m paddle.distributed.launch --gpus=6 gino.py
seed: 0
lr: 0.0003 # 0.0005
lr_cd: 0.01
weight_list: [20.0, 1.0] # [20.0, 1.0]
batch_size: 1
num_epochs: 60 # 1000
finetuning_epochs: 51
output_dir: ${hydra:run.dir}
# mode: "train"  # train, test
mode: "inference"
# state: /home/chenkai26/Paddle-AeroSimOpt/trainedModel/models/GNOFNOGNO_all_849.pdparams  # null
save_per_epoch: 20
save_eval_results: true
resume_ep: -1

# inference params
state: null
pd_path: null
reason_input_path: null # /pre_process/{case_id}
reason_output_path: null # /reason_output/reason_{taskId}
pre_output_path: null # /pre_output/{数据集id} for bounds txt files
# gpu: null
