[tool.black]
line-length = 119
target_version = ['py310']

[tool.ruff]
line-length = 119

[tool.ruff.lint]
# Ignored rules:
#   "E501" -> line length violation
#   "F821" -> undefined named in type annotation (e.g. Literal["something"])
ignore = ["E501", "F821"]
select = ["E", "F", "I", "W"]

[tool.ruff.lint.isort]
lines-after-imports = 2
known-first-party = ["dyffusion"]
