hydra:
  run:
    # dynamic output directory according to running time and override name
    dir: outputs-newdata/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working direcotry unchanged
  sweep:
    # output directory for multirun
    dir: ${hydra.run.dir}
    subdir: ./

# Setting
mode: "test"
seed: 0
output_dir: ${hydra:run.dir}
device: "gpu:6"
dtype: float32

# DataSet
DATA:
  path: "./Dataset"
  task: "full"
  download: False
  sample_points: 10000
  batch_size: 2000
  shuffle: True
  boundary_line_ratio: 0.2
  




# Model
mlp: False
kan: True
model: "1B-63-1T-2-KANONet"
MLPMODEL:
  branch1_in: 63
  branch1_hidden: [512, 256, 256, 128, 128]
  trunk_in: 2
  trunk_hidden: [128, 256, 256, 128, 128]
KANMODEL:
  width_branch1: [63, 128, 128, 64]
  grid_range_b1: [-3.0, 3.0]
  grid_size_b1: 50

  width_trunk: [2, 128, 128, 64]
  grid_range_t: [-1.5, 4.0]
  grid_size_t: 50

  # width_branch2: [2, 10, 40]
  # grid_range_b2: [-1.8, 1.8]
  # grid_size_b2: 100

  # width_branch3: [1, 10, 10, 40]
  # grid_range_b3: [-1, 3.0]
  # grid_size_b3: 45

  

  

# Hyper-parameters
# train
epochs: 500
lr: 0.001
save_freq: 10
enable_ddp: false
resume_ep: -1
checkpoint: "./outputs-newdata/2025-04-28/06-07-50/1B-63-1T-2-KANONet_best.pdparams"

# eval
pred_ckpt: null
