hydra:
  run:
    # dynamic output directory according to running time and override name
    dir: trainedModel/${now:%Y-%m-%d-%H-%M-%S}-${mode}
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working direcotry unchaned
  sweep:
    # output directory for multirun
    dir: ${hydra.run.dir}
    subdir: ./

# model
model: "GNOFNOGNO_all"
radius_in: 0.04  # 0.045
radius_out: 0.04  # 0.045
embed_dim: 32  # 32
hidden_channels: [64, 64] # [64, 64]
in_channels: 2
out_channels: [1,3] # pressure + wss
fno_modes: [32, 32, 32] # [32, 32, 32]
fno_hidden_channels: 64 # 64
fno_out_channels: 64 # 64
weighted_kernel: false
max_in_points: 100000
subsample_train: 6 # 1
subsample_eval: 1 # only set to 1 can get right Cd truth
out_keys: ["pressure","wallshearstress"]
sdf_spatial_resolution: [64, 64, 64] # or [64, 64, 64]

# data
data_module: "SAE"
data_path: "/home/chenkai26/dataset/zhongche-paddle/"
# data_path: "/home/chenkai26/dataset/SAE-Variable-three-paras"
n_train_num: 1 # 862
n_val_num: 1 # 
n_test_num: 103 # 43
only_save_sdf: false  # generate sdf&closest_points or training
lazy_loading: true  # load all data into memory or not

# settings
enable_ddp: true
devices: [1, 2]  # python -m paddle.distributed.launch --gpus=6 gino.py
seed: 0
lr: 0.0003 # 0.0005
weight_list: [20.0, 1.0] # [20.0, 1.0]
batch_size: 1
num_epochs: 1000 # 1000
output_dir: ${hydra:run.dir}
# mode: "train"  # train, test
mode: "test"
# state: null
state: '/home/chenkai26/Paddle-AeroSimOpt/trainedModel/models/GNOFNOGNO_all_999.pdparams'  # null
# inference_model: '/home/chenkai26/Paddle-AeroSimOpt/trainedModel/models/inference_gino.pdmodel'
# inference_params: '/home/chenkai26/Paddle-AeroSimOpt/trainedModel/models/inference_gino.pdparams'
save_per_epoch: 200
save_eval_results: false
resume_ep: -1
